# controller_joint_names: ['motor_wheel_right', 'motor_wheel_left', 'motor_wheel_back', ]

rover:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    mobile_base_controller:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel: 'motor_wheel_left'
      right_wheel: 'motor_wheel_right'
      pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
      twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

      wheel_radius : 0.5

    # # Position Controllers ---------------------------------------
    # motor_wheel_right_joint_position_controller:
    #   type: effort_controllers/JointPositionController
    #   joint: motor_wheel_right
    #   pid: {p: 15.0, i: 1.0, d: 0.0}
    # motor_wheel_left_joint_position_controller:
    #   type: effort_controllers/JointPositionController
    #   joint: motor_wheel_left
    #   pid: {p: 15.0, i: 1.0, d: 0.0}
